# nixpacks.toml
[phases.setup]
nixPkgs = ["nodejs-18_x", "python3"]

[phases.install]
cmds = ["npm install --production=false"]

[phases.build]
cmds = ["npm run build || true"]

[start]
cmd = "npm start" 